package com.my.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.my.mybatis.annotation.User;
import com.my.mybatis.model.EEmpiLog;
import com.my.mybatis.model.EEmpiLogExample;

public interface EEmpiLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
	@User(name="cz")
    int countByExample(EEmpiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int deleteByExample(EEmpiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int insert(EEmpiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int insertSelective(EEmpiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    List<EEmpiLog> selectByExample(EEmpiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    EEmpiLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int updateByExampleSelective(@Param("record") EEmpiLog record, @Param("example") EEmpiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int updateByExample(@Param("record") EEmpiLog record, @Param("example") EEmpiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int updateByPrimaryKeySelective(EEmpiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    int updateByPrimaryKey(EEmpiLog record);
}