package com.my.mybatis.model;

import java.util.Date;

public class EEmpiLog extends ShareBase{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.ID_
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.SOURCE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.TARGET
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.EVENT_NAME_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String eventNameCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.RESULT_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.ERROR_CATEGORY
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String errorCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.ERROR_TYPE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String errorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.ERROR_POSITION
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String errorPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.EMPI
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String empi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.EVENT_TIME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private Date eventTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.CARD_TYPE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.CARD_NO
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.RESIDENT_NAME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String residentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.ORG_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column E_EMPI_LOG.ORG_NAME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    private String orgName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.ID_
     *
     * @return the value of E_EMPI_LOG.ID_
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.ID_
     *
     * @param id the value for E_EMPI_LOG.ID_
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.SOURCE
     *
     * @return the value of E_EMPI_LOG.SOURCE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.SOURCE
     *
     * @param source the value for E_EMPI_LOG.SOURCE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.TARGET
     *
     * @return the value of E_EMPI_LOG.TARGET
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.TARGET
     *
     * @param target the value for E_EMPI_LOG.TARGET
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.EVENT_NAME_CODE
     *
     * @return the value of E_EMPI_LOG.EVENT_NAME_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getEventNameCode() {
        return eventNameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.EVENT_NAME_CODE
     *
     * @param eventNameCode the value for E_EMPI_LOG.EVENT_NAME_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setEventNameCode(String eventNameCode) {
        this.eventNameCode = eventNameCode == null ? null : eventNameCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.RESULT_CODE
     *
     * @return the value of E_EMPI_LOG.RESULT_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.RESULT_CODE
     *
     * @param resultCode the value for E_EMPI_LOG.RESULT_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.ERROR_CATEGORY
     *
     * @return the value of E_EMPI_LOG.ERROR_CATEGORY
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getErrorCategory() {
        return errorCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.ERROR_CATEGORY
     *
     * @param errorCategory the value for E_EMPI_LOG.ERROR_CATEGORY
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setErrorCategory(String errorCategory) {
        this.errorCategory = errorCategory == null ? null : errorCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.ERROR_TYPE
     *
     * @return the value of E_EMPI_LOG.ERROR_TYPE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getErrorType() {
        return errorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.ERROR_TYPE
     *
     * @param errorType the value for E_EMPI_LOG.ERROR_TYPE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setErrorType(String errorType) {
        this.errorType = errorType == null ? null : errorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.ERROR_POSITION
     *
     * @return the value of E_EMPI_LOG.ERROR_POSITION
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getErrorPosition() {
        return errorPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.ERROR_POSITION
     *
     * @param errorPosition the value for E_EMPI_LOG.ERROR_POSITION
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setErrorPosition(String errorPosition) {
        this.errorPosition = errorPosition == null ? null : errorPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.EMPI
     *
     * @return the value of E_EMPI_LOG.EMPI
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getEmpi() {
        return empi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.EMPI
     *
     * @param empi the value for E_EMPI_LOG.EMPI
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setEmpi(String empi) {
        this.empi = empi == null ? null : empi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.EVENT_TIME
     *
     * @return the value of E_EMPI_LOG.EVENT_TIME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public Date getEventTime() {
        return eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.EVENT_TIME
     *
     * @param eventTime the value for E_EMPI_LOG.EVENT_TIME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.CARD_TYPE
     *
     * @return the value of E_EMPI_LOG.CARD_TYPE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.CARD_TYPE
     *
     * @param cardType the value for E_EMPI_LOG.CARD_TYPE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.CARD_NO
     *
     * @return the value of E_EMPI_LOG.CARD_NO
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.CARD_NO
     *
     * @param cardNo the value for E_EMPI_LOG.CARD_NO
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.RESIDENT_NAME
     *
     * @return the value of E_EMPI_LOG.RESIDENT_NAME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getResidentName() {
        return residentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.RESIDENT_NAME
     *
     * @param residentName the value for E_EMPI_LOG.RESIDENT_NAME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setResidentName(String residentName) {
        this.residentName = residentName == null ? null : residentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.ORG_CODE
     *
     * @return the value of E_EMPI_LOG.ORG_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.ORG_CODE
     *
     * @param orgCode the value for E_EMPI_LOG.ORG_CODE
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column E_EMPI_LOG.ORG_NAME
     *
     * @return the value of E_EMPI_LOG.ORG_NAME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column E_EMPI_LOG.ORG_NAME
     *
     * @param orgName the value for E_EMPI_LOG.ORG_NAME
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }
}