package com.my.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EEmpiLogExample extends ShareBase{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
	

	protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public EEmpiLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID_ like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID_ not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andTargetIsNull() {
            addCriterion("TARGET is null");
            return (Criteria) this;
        }

        public Criteria andTargetIsNotNull() {
            addCriterion("TARGET is not null");
            return (Criteria) this;
        }

        public Criteria andTargetEqualTo(String value) {
            addCriterion("TARGET =", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotEqualTo(String value) {
            addCriterion("TARGET <>", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThan(String value) {
            addCriterion("TARGET >", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET >=", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLessThan(String value) {
            addCriterion("TARGET <", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLessThanOrEqualTo(String value) {
            addCriterion("TARGET <=", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetLike(String value) {
            addCriterion("TARGET like", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotLike(String value) {
            addCriterion("TARGET not like", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetIn(List<String> values) {
            addCriterion("TARGET in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotIn(List<String> values) {
            addCriterion("TARGET not in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetBetween(String value1, String value2) {
            addCriterion("TARGET between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotBetween(String value1, String value2) {
            addCriterion("TARGET not between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeIsNull() {
            addCriterion("EVENT_NAME_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeIsNotNull() {
            addCriterion("EVENT_NAME_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeEqualTo(String value) {
            addCriterion("EVENT_NAME_CODE =", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeNotEqualTo(String value) {
            addCriterion("EVENT_NAME_CODE <>", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeGreaterThan(String value) {
            addCriterion("EVENT_NAME_CODE >", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_NAME_CODE >=", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeLessThan(String value) {
            addCriterion("EVENT_NAME_CODE <", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeLessThanOrEqualTo(String value) {
            addCriterion("EVENT_NAME_CODE <=", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeLike(String value) {
            addCriterion("EVENT_NAME_CODE like", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeNotLike(String value) {
            addCriterion("EVENT_NAME_CODE not like", value, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeIn(List<String> values) {
            addCriterion("EVENT_NAME_CODE in", values, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeNotIn(List<String> values) {
            addCriterion("EVENT_NAME_CODE not in", values, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeBetween(String value1, String value2) {
            addCriterion("EVENT_NAME_CODE between", value1, value2, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andEventNameCodeNotBetween(String value1, String value2) {
            addCriterion("EVENT_NAME_CODE not between", value1, value2, "eventNameCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNull() {
            addCriterion("RESULT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNotNull() {
            addCriterion("RESULT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andResultCodeEqualTo(String value) {
            addCriterion("RESULT_CODE =", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotEqualTo(String value) {
            addCriterion("RESULT_CODE <>", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThan(String value) {
            addCriterion("RESULT_CODE >", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RESULT_CODE >=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThan(String value) {
            addCriterion("RESULT_CODE <", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThanOrEqualTo(String value) {
            addCriterion("RESULT_CODE <=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLike(String value) {
            addCriterion("RESULT_CODE like", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotLike(String value) {
            addCriterion("RESULT_CODE not like", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeIn(List<String> values) {
            addCriterion("RESULT_CODE in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotIn(List<String> values) {
            addCriterion("RESULT_CODE not in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeBetween(String value1, String value2) {
            addCriterion("RESULT_CODE between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotBetween(String value1, String value2) {
            addCriterion("RESULT_CODE not between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryIsNull() {
            addCriterion("ERROR_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryIsNotNull() {
            addCriterion("ERROR_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryEqualTo(String value) {
            addCriterion("ERROR_CATEGORY =", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryNotEqualTo(String value) {
            addCriterion("ERROR_CATEGORY <>", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryGreaterThan(String value) {
            addCriterion("ERROR_CATEGORY >", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_CATEGORY >=", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryLessThan(String value) {
            addCriterion("ERROR_CATEGORY <", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryLessThanOrEqualTo(String value) {
            addCriterion("ERROR_CATEGORY <=", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryLike(String value) {
            addCriterion("ERROR_CATEGORY like", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryNotLike(String value) {
            addCriterion("ERROR_CATEGORY not like", value, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryIn(List<String> values) {
            addCriterion("ERROR_CATEGORY in", values, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryNotIn(List<String> values) {
            addCriterion("ERROR_CATEGORY not in", values, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryBetween(String value1, String value2) {
            addCriterion("ERROR_CATEGORY between", value1, value2, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorCategoryNotBetween(String value1, String value2) {
            addCriterion("ERROR_CATEGORY not between", value1, value2, "errorCategory");
            return (Criteria) this;
        }

        public Criteria andErrorTypeIsNull() {
            addCriterion("ERROR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andErrorTypeIsNotNull() {
            addCriterion("ERROR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andErrorTypeEqualTo(String value) {
            addCriterion("ERROR_TYPE =", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeNotEqualTo(String value) {
            addCriterion("ERROR_TYPE <>", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeGreaterThan(String value) {
            addCriterion("ERROR_TYPE >", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_TYPE >=", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeLessThan(String value) {
            addCriterion("ERROR_TYPE <", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeLessThanOrEqualTo(String value) {
            addCriterion("ERROR_TYPE <=", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeLike(String value) {
            addCriterion("ERROR_TYPE like", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeNotLike(String value) {
            addCriterion("ERROR_TYPE not like", value, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeIn(List<String> values) {
            addCriterion("ERROR_TYPE in", values, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeNotIn(List<String> values) {
            addCriterion("ERROR_TYPE not in", values, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeBetween(String value1, String value2) {
            addCriterion("ERROR_TYPE between", value1, value2, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorTypeNotBetween(String value1, String value2) {
            addCriterion("ERROR_TYPE not between", value1, value2, "errorType");
            return (Criteria) this;
        }

        public Criteria andErrorPositionIsNull() {
            addCriterion("ERROR_POSITION is null");
            return (Criteria) this;
        }

        public Criteria andErrorPositionIsNotNull() {
            addCriterion("ERROR_POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andErrorPositionEqualTo(String value) {
            addCriterion("ERROR_POSITION =", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionNotEqualTo(String value) {
            addCriterion("ERROR_POSITION <>", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionGreaterThan(String value) {
            addCriterion("ERROR_POSITION >", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_POSITION >=", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionLessThan(String value) {
            addCriterion("ERROR_POSITION <", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionLessThanOrEqualTo(String value) {
            addCriterion("ERROR_POSITION <=", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionLike(String value) {
            addCriterion("ERROR_POSITION like", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionNotLike(String value) {
            addCriterion("ERROR_POSITION not like", value, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionIn(List<String> values) {
            addCriterion("ERROR_POSITION in", values, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionNotIn(List<String> values) {
            addCriterion("ERROR_POSITION not in", values, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionBetween(String value1, String value2) {
            addCriterion("ERROR_POSITION between", value1, value2, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andErrorPositionNotBetween(String value1, String value2) {
            addCriterion("ERROR_POSITION not between", value1, value2, "errorPosition");
            return (Criteria) this;
        }

        public Criteria andEmpiIsNull() {
            addCriterion("EMPI is null");
            return (Criteria) this;
        }

        public Criteria andEmpiIsNotNull() {
            addCriterion("EMPI is not null");
            return (Criteria) this;
        }

        public Criteria andEmpiEqualTo(String value) {
            addCriterion("EMPI =", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiNotEqualTo(String value) {
            addCriterion("EMPI <>", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiGreaterThan(String value) {
            addCriterion("EMPI >", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiGreaterThanOrEqualTo(String value) {
            addCriterion("EMPI >=", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiLessThan(String value) {
            addCriterion("EMPI <", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiLessThanOrEqualTo(String value) {
            addCriterion("EMPI <=", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiLike(String value) {
            addCriterion("EMPI like", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiNotLike(String value) {
            addCriterion("EMPI not like", value, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiIn(List<String> values) {
            addCriterion("EMPI in", values, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiNotIn(List<String> values) {
            addCriterion("EMPI not in", values, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiBetween(String value1, String value2) {
            addCriterion("EMPI between", value1, value2, "empi");
            return (Criteria) this;
        }

        public Criteria andEmpiNotBetween(String value1, String value2) {
            addCriterion("EMPI not between", value1, value2, "empi");
            return (Criteria) this;
        }

        public Criteria andEventTimeIsNull() {
            addCriterion("EVENT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEventTimeIsNotNull() {
            addCriterion("EVENT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEventTimeEqualTo(Date value) {
            addCriterion("EVENT_TIME =", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeNotEqualTo(Date value) {
            addCriterion("EVENT_TIME <>", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeGreaterThan(Date value) {
            addCriterion("EVENT_TIME >", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("EVENT_TIME >=", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeLessThan(Date value) {
            addCriterion("EVENT_TIME <", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeLessThanOrEqualTo(Date value) {
            addCriterion("EVENT_TIME <=", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeIn(List<Date> values) {
            addCriterion("EVENT_TIME in", values, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeNotIn(List<Date> values) {
            addCriterion("EVENT_TIME not in", values, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeBetween(Date value1, Date value2) {
            addCriterion("EVENT_TIME between", value1, value2, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeNotBetween(Date value1, Date value2) {
            addCriterion("EVENT_TIME not between", value1, value2, "eventTime");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("CARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("CARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("CARD_TYPE =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("CARD_TYPE <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("CARD_TYPE >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("CARD_TYPE <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("CARD_TYPE like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("CARD_TYPE not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("CARD_TYPE in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("CARD_TYPE not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("CARD_TYPE between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("CARD_TYPE not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("CARD_NO =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("CARD_NO <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("CARD_NO >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NO >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("CARD_NO <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("CARD_NO <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("CARD_NO like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("CARD_NO not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("CARD_NO in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("CARD_NO not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("CARD_NO between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("CARD_NO not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andResidentNameIsNull() {
            addCriterion("RESIDENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andResidentNameIsNotNull() {
            addCriterion("RESIDENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andResidentNameEqualTo(String value) {
            addCriterion("RESIDENT_NAME =", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameNotEqualTo(String value) {
            addCriterion("RESIDENT_NAME <>", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameGreaterThan(String value) {
            addCriterion("RESIDENT_NAME >", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameGreaterThanOrEqualTo(String value) {
            addCriterion("RESIDENT_NAME >=", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameLessThan(String value) {
            addCriterion("RESIDENT_NAME <", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameLessThanOrEqualTo(String value) {
            addCriterion("RESIDENT_NAME <=", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameLike(String value) {
            addCriterion("RESIDENT_NAME like", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameNotLike(String value) {
            addCriterion("RESIDENT_NAME not like", value, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameIn(List<String> values) {
            addCriterion("RESIDENT_NAME in", values, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameNotIn(List<String> values) {
            addCriterion("RESIDENT_NAME not in", values, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameBetween(String value1, String value2) {
            addCriterion("RESIDENT_NAME between", value1, value2, "residentName");
            return (Criteria) this;
        }

        public Criteria andResidentNameNotBetween(String value1, String value2) {
            addCriterion("RESIDENT_NAME not between", value1, value2, "residentName");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("ORG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("ORG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("ORG_CODE =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("ORG_CODE <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("ORG_CODE >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CODE >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("ORG_CODE <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("ORG_CODE <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("ORG_CODE like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("ORG_CODE not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("ORG_CODE in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("ORG_CODE not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("ORG_CODE between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("ORG_CODE not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNull() {
            addCriterion("ORG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNotNull() {
            addCriterion("ORG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEqualTo(String value) {
            addCriterion("ORG_NAME =", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotEqualTo(String value) {
            addCriterion("ORG_NAME <>", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThan(String value) {
            addCriterion("ORG_NAME >", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NAME >=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThan(String value) {
            addCriterion("ORG_NAME <", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThanOrEqualTo(String value) {
            addCriterion("ORG_NAME <=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLike(String value) {
            addCriterion("ORG_NAME like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotLike(String value) {
            addCriterion("ORG_NAME not like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameIn(List<String> values) {
            addCriterion("ORG_NAME in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotIn(List<String> values) {
            addCriterion("ORG_NAME not in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameBetween(String value1, String value2) {
            addCriterion("ORG_NAME between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotBetween(String value1, String value2) {
            addCriterion("ORG_NAME not between", value1, value2, "orgName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 18 08:37:12 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table E_EMPI_LOG
     *
     * @mbggenerated Fri Apr 18 08:37:12 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
        
        
    }
}